macro(setup_llvm)
    if (NOT LLVM_CONFIG_BINARY)
        find_program(LLVM_CONFIG llvm-config)
        if (LLVM_CONFIG STREQUAL LLVM_CONFIG-NOTFOUND)
            message(WARNING "Unable to find local llvm-config")
        else ()
            message("Using local clang")
        endif ()
    else ()
        message("Using manually specified clang ${LLVM_CONFIG_BINARY} (LLVM_CONFIG_BINARY)")
    endif ()
endmacro()